version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: auditDB
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "postgrespw"
      POSTGRES_DB: "devdb"
    volumes:
      - auditDB-data:/var/lib/postgresql/data
    restart: unless-stopped
  auditserver:
    build: .
    container_name: auditService
    ports:
      - "50051:50051"
    links:
      - postgres
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  auditDB-data: