version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "quote-server-adaptor"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "cli"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "lean"
    schedule:
      interval: "daily"