version: '3.8.0'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  quote-server-adaptor:
    image: ghcr.io/marcusdunn/day-trader/quote-server-adaptor:latest
    environment:
      QUOTE_SERVER_URI: quoteserver.seng.uvic.ca:4000
      OTEL_COLLECTOR_URI: jaeger:14268
  distribution-server:
    image: ghcr.io/marcusdunn/day-trader/distribution-server:latest
    environment:
      QUOTE_SERVER_URI: quote-server-adaptor:5000
      OTEL_EXPORTER_URI: jaeger:14268
    ports:
      - "80:80"