version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'
  postgres:
    image: postgres:latest
    shm_size: 14g
    environment:
      POSTGRES_USER: "daytrader"
      POSTGRES_PASSWORD: "daytrader"
    command: postgres -c max_connections=5010 -c fsync=off -c synchronous_commit=off -c full_page_writes=false -c effective_cache_size=8GB
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U daytrader -d daytrader'"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  lean:
    shm_size: 4g
    image: ghcr.io/marcusdunn/day-trader/lean
    environment:
      DATABASE_URL: postgres://daytrader:daytrader@postgres:5432/daytrader
      QUOTE_CLIENT_ADDR: http://quote-server-adaptor:50051
      TRACE_ID_RATIO: 0.005
      SERVER_ADDR: 0.0.0.0:8000
      RUST_LOG: "none,lean=info"
      DATABASE_MAX_CONNECTIONS: 5000
      TRIGGER_CHANNEL_SIZE: 10000
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      DATABASE_CONNECTION_TIMEOUT_SECONDS: 5
    depends_on:
      postgres:
        condition: service_healthy
      quote-server-adaptor:
        condition: service_started
    init: true
    ports:
      - "8000:8000"
  quote-server-adaptor:
    image: ghcr.io/marcusdunn/day-trader/quote-server-adaptor
    init: true
    environment:
      QUOTE_SERVER_URI: FAKE
      RUST_LOG: "none,quote_server_adaptor=info"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
  swift-trader-frontend:
    image: ghcr.io/marcusdunn/day-trader/swifttrader
    container_name: swift-trader-frontend
    environment:
      - DUMMY_DATA=false
      - FRONTEND_URL=http://swift-trader-frontend:3000/
      - transactionURI=lean:8000
    ports:
      - "80:3000"
