version: '3.8.0'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
    environment:
      COLLECTOR_OTLP_ENABLED: true
  quote-server-adaptor:
    image: ghcr.io/marcusdunn/day-trader/quote-server-adaptor:latest
    environment:
      QUOTE_SERVER_URI: FAKE
      OTEL_EXPORTER_URI: http://jaeger:4317
      SERVER_ADDR: 0.0.0.0:50051
  distribution-server:
    image: ghcr.io/marcusdunn/day-trader/distribution-server:latest
    environment:
      QUOTE_SERVER_URI: quote-server-adaptor:50051
      OTEL_EXPORTER_URI: jaeger:4317
    ports:
      - "80:80"