version: '3.8.0'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
    environment:
      COLLECTOR_OTLP_ENABLED: true
  quote-server-adaptor:
    # image: ghcr.io/marcusdunn/day-trader/quote-server-adaptor:latest
    build:
      context: .
      dockerfile: quote-server-adaptor.Dockerfile
    environment:
      QUOTE_SERVER_URI: quoteserve.seng.uvic.ca:4444
      OTEL_EXPORTER_URI: http://jaeger:4317
      SERVER_ADDR: 0.0.0.0:50051
      RUST_LOG: quote_server_adaptor
      LOG_ADDR: http://auditserver:50051
    depends_on:
      auditserver:
        condition: service_healthy
    init: true
  distribution-server:
    image: ghcr.io/marcusdunn/day-trader/distribution-server:latest
    environment:
      QUOTE_SERVER_URI: quote-server-adaptor:50051
      OTEL_EXPORTER_URI: jaeger:4317
      TRANSACTION_SERVER_URI: transactionserver:50051
      TRIGGER_SERVER_URI: transactionserver:50051
      LOG_SERVER_URI: auditserver:50051
    ports:
      - "80:80"
    links:
      - transactionserver
      - auditserver
      - jaeger
      - quote-server-adaptor
    depends_on:
      transactionserver:
        condition: service_started
      quote-server-adaptor:
        condition: service_started
      auditserver:
        condition: service_started
      jaeger:
        condition: service_started
  transactionDB:
    image: postgres:latest
    container_name: transactionDB
    hostname: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "postgrespw"
      POSTGRES_DB: "devdb"
    restart: unless-stopped
    volumes:
      - transactionDB-data:/var/lib/postgresql/data
  transactionserver:
    image: ghcr.io/marcusdunn/day-trader/transaction:latest
    depends_on:
      - transactionDB
    environment:
      QuoteURI: quote-server-adaptor:50051
    restart: unless-stopped
  auditDB:
    image: postgres:latest
    container_name: auditDB
    hostname: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "postgrespw"
      POSTGRES_DB: "devdb"
    volumes:
      - auditDB-data:/var/lib/postgresql/data
    restart: unless-stopped
  auditserver:
    image: ghcr.io/marcusdunn/day-trader/audit:latest
    container_name: auditService
    depends_on:
      - auditDB
    links:
      - auditDB
    restart: unless-stopped
    healthcheck:
      # grpcurl -plaintext -d '{"user_id": "healthcheck"}' -format json -format-error -proto ./src/proto/day-trader-copy.proto localhost:50051 day_trader.Log.DisplaySummary | jq
      test: ["CMD-SHELL", "grpcurl -plaintext -d '{\"user_id\": \"healthcheck\"}' -format json -format-error -proto ./src/proto/day-trader-copy.proto 0.0.0.0:50051 day_trader.Log.DisplaySummary | jq"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
volumes:
  transactionDB-data:
  auditDB-data: