export const BuyTriggers = [
  {
    username: "John",
    stock: "ABC",
    buyAmount: 5000.00,
    triggerAmount: 542.25,
  },
  {
    username: "Jane",
    stock: "XYZ",
    buyAmount: 123.45,
    triggerAmount: null,
  },
  {
    username: "Bob",
    stock: "DEF",
    buyAmount: 5000.00,
    triggerAmount: 987.65,
  },
  {
    username: "Alice",
    stock: "GHI",
    buyAmount: 654.32,
    triggerAmount: null,
  },
  {
    username: "David",
    stock: "JKL",
    buyAmount: 5000.00,
    triggerAmount: 321.09,
  },
  {
    username: "Samantha",
    stock: "MNO",
    buyAmount: 456.78,
    triggerAmount: null,
  },
  {
    username: "Tom",
    stock: "PQR",
    buyAmount: 5000.00,
    triggerAmount: 789.01,
  },
  {
    username: "Emily",
    stock: "STU",
    buyAmount: 234.56,
    triggerAmount: null,
  },
  {
    username: "Mike",
    stock: "VWX",
    buyAmount: 5000.00,
    triggerAmount: 890.12,
  },
  {
    username: "Jessica",
    stock: "YZA",
    buyAmount: 567.89,
    triggerAmount: null,
  },
  {
    username: "William",
    stock: "BCD",
    buyAmount: 5000.00,
    triggerAmount: 432.1,
  },
  {
    username: "Linda",
    stock: "EFG",
    buyAmount: 765.43,
    triggerAmount: null,
  },
  {
    username: "Chris",
    stock: "HIJ",
    buyAmount: 5000.00,
    triggerAmount: 901.23,
  },
  {
    username: "Megan",
    stock: "KLM",
    buyAmount: 234.56,
    triggerAmount: null,
  },
  {
    username: "Jason",
    stock: "NOP",
    buyAmount: 5000.00,
    triggerAmount: 789.01,
  },
];
