export const ErrorEvents = [
    {
      timestamp: 1167631206000,
      server: "CLT2",
      command: "SELL",
      username: "bob",
      stockSymbol: "GHI",
      funds: 1000,
      errorMessage: "Account bob does not exist",
    },
    {
      timestamp: 1167631207000,
      server: "CLT1",
      command: "BUY",
      username: "alice",
      stockSymbol: "ABC",
      funds: 2000,
      errorMessage: "Insufficient funds for alice",
    },
    {
      timestamp: 1167631208000,
      server: "CLT2",
      command: "SELL",
      username: "john",
      stockSymbol: "DEF",
      funds: 3000,
      errorMessage: "Account john is suspended",
    },
    {
      timestamp: 1167631209000,
      server: "CLT1",
      command: "BUY",
      username: "peter",
      stockSymbol: "GHI",
      funds: 4000,
      errorMessage: "Invalid stock symbol",
    },
    {
      timestamp: 1167631210000,
      server: "CLT2",
      command: "SELL",
      username: "lisa",
      stockSymbol: "XYZ",
      funds: 5000,
      errorMessage: "Account lisa has exceeded the transaction limit",
    },
    {
      timestamp: 1167631211000,
      server: "CLT1",
      command: "BUY",
      username: "will",
      stockSymbol: "ABC",
      funds: 6000,
      errorMessage: "Account will is blocked",
    },
    {
      timestamp: 1167631212000,
      server: "CLT2",
      command: "SELL",
      username: "david",
      stockSymbol: "DEF",
      funds: 7000,
      errorMessage: "Account david has been deleted",
    },
    {
      timestamp: 1167631213000,
      server: "CLT1",
      command: "BUY",
      username: "emily",
      stockSymbol: "GHI",
      funds: 8000,
      errorMessage: "Account emily has no funds",
    },
    {
      timestamp: 1167631214000,
      server: "CLT2",
      command: "SELL",
      username: "mike",
      stockSymbol: "XYZ",
      funds: 9000,
      errorMessage: "Account mike has been blocked",
    },
    {
      timestamp: 1167631215000,
      server: "CLT1",
      command: "BUY",
      username: "olivia",
      stockSymbol: "ABC",
      funds: 10000,
      errorMessage: "Account olivia is expired",
    },
    {
      timestamp: 1167631216000,
      server: "CLT2",
      command: "SELL",
      username: "sam",
      stockSymbol: "DEF",
      funds: 11000,
      errorMessage: "Account sam has exceeded the balance limit",
    },
    {
      timestamp: 1167631217000,
      server: "CLT1",
      command: "BUY",
      username: "jane",
      stockSymbol: "GHI",
      funds: 12000,
      errorMessage: "Invalid username",
    },
]