export const Logs = [
  {
    action: "BUY",
    user: "john",
    amount: 2514.15,
    stock: "ABC",
    shareprice: 2514.15,
    shares_bought: 1,
  },
  {
    action: "SELL",
    user: "jane",
    amount: 1269.37,
    stock: "XYZ",
    shareprice: 63.47,
    shares_bought: 20,
  },
  {
    action: "BUY",
    user: "sam",
    amount: 712.19,
    stock: "DEF",
    shareprice: 356.09,
    shares_bought: 2,
  },
  {
    action: "SELL",
    user: "alice",
    amount: 435.22,
    stock: "MNO",
    shareprice: 21.76,
    shares_bought: 20,
  },
  {
    action: "BUY",
    user: "bob",
    amount: 987.65,
    stock: "PQR",
    shareprice: 123.46,
    shares_bought: 8,
  },
  {
    action: "SELL",
    user: "emily",
    amount: 2543.21,
    stock: "GHI",
    shareprice: 127.16,
    shares_bought: 20,
  },
  {
    action: "BUY",
    user: "dave",
    amount: 842.56,
    stock: "JKL",
    shareprice: 42.13,
    shares_bought: 20,
  },
  {
    action: "SELL",
    user: "sarah",
    amount: 117.89,
    stock: "TUV",
    shareprice: 11.79,
    shares_bought: 10,
  },
  {
    action: "BUY",
    user: "tom",
    amount: 634.27,
    stock: "STU",
    shareprice: 158.57,
    shares_bought: 4,
  },
  {
    action: "SELL",
    user: "mike",
    amount: 2080.34,
    stock: "NOP",
    shareprice: 115.57,
    shares_bought: 18,
  },
  {
    action: "BUY",
    user: "lisa",
    amount: 423.08,
    stock: "VWX",
    shareprice: 47.01,
    shares_bought: 9,
  },
];
