version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: transactionDB
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "postgrespw"
      POSTGRES_DB: "devdb"
    restart: unless-stopped
  transactionserver:
    image: transactionserver
    container_name: transactionService
    ports:
      - 50051:50051
    links:
      - postgres
    depends_on:
      - postgres
    restart: unless-stopped
