on:
  push:
    branches: ["main"]
  pull_request: {}
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: CLI CI
jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      cli: ${{ steps.filter.outputs.cli }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            cli:
              - 'cli/**'
              - 'protos/**'
  test:
    name: Tests
    needs: changes
    if: ${{ needs.changes.outputs.cli == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Run fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path cli/Cargo.toml --all -- --check
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path cli/Cargo.toml -- -D warnings
      - name: Run clippy
        with:
          command: clippy
          args: --manifest-path cli/Cargo.toml -- -D warnings
      - name: Run test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path cli/Cargo.toml